# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl).
{
    "name": "HR UAE - Project as Department",
    "version": "18.0.1.0.0",
    "license": "LGPL-3",
    "category": "Human Resources",
    "summary": "Use HR departments as operational Projects while keeping analytic project allocations as project cost centers.",
    "author": "HrProject Team",
    "website": "https://example.com/hr-uae",
    "depends": [
        "hr_uae_reports",
        "hr_uae_payroll",
        "hr_uae_flights",
        "hr_uae_documents",
        "hr_uae_salary_adjustment",
        "hr_uae_termination",
        "hr_uae_leaves",
        "hr_contract",
        "hr_expense",
        "hr_holidays",
        "hr_org_chart",
        "hr_skills",
    ],
    "data": [
        "views/hr_uae_project_menus.xml",
        "views/hr_department_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_uae_transaction_views.xml",
        "views/hr_ui_label_views.xml",
        "report/hr_uae_report_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "hr_uae_project_department/static/src/live_dashboard/payroll_project_patch.js",
            "hr_uae_project_department/static/src/live_dashboard/dashboard_project_labels.xml",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
